spring:
  cloud:
    function:
#      definition: uppercase|echo
      definition: evenLogger;oddLogger
    stream:
      bindings:
        evenLogger-in-0:
          destination: router-out-0
          group: even
        oddLogger-in-0:
          destination: router-out-1
          group: odd
